# 基础镜像
FROM python:3.12.8

# 维护者信息
MAINTAINER wohaokun <791426617@email.com>

# 设置环境变量
ENV APP_HOME=/app

# 工作目录
WORKDIR /app

# 复制应用文件
COPY requirements.txt .
RUN pip install -r requirements.txt

# 运行命令
RUN apt-get update && \
    apt-get install -y nodejs

RUN

# 暴露端口
EXPOSE 6000

# 容器启动时执行的命令
# CMD ["node", "app.js"]
