# 基础镜像
FROM python:3.12.8

# 维护者信息
LABEL maintainer="wohaokun <791426617@email.com>"


# 设置环境变量
# 确保 Python 输出不被缓存
ENV PYTHONUNBUFFERED=1       
# 不生成 .pyc 文件 
ENV PYTHONDONTWRITEBYTECODE=1 
ENV APP_HOME=/app

# 创建非 root 用户
RUN useradd -m -s /bin/bash worker

# 工作目录
WORKDIR $APP_HOME

# 复制应用文件
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# 设置权限
RUN chown -R worker:worker $APP_HOME

# 切换到非 root 用户
USER worker

# 暴露端口
EXPOSE 6000
